services:
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: kolesiki_db
            POSTGRES_USER: kolesiki_user
            POSTGRES_PASSWORD: your_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://kolesiki_user:your_password@db:5432/kolesiki_db

volumes:
    postgres_data:
