version: "3.8"

services:
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: shop
            POSTGRES_USER: shop_user
            POSTGRES_PASSWORD: shop_pass
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://shop_user:shop_pass@db:5432/shop

volumes:
    postgres_data:
