services:
    db:
        image: postgres:15
        environment:
            POSTGRES_DB: kolesiki_db
            POSTGRES_USER: kolesiki_user
            POSTGRES_PASSWORD: your_password
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U kolesiki_user -d kolesiki_db"]
            interval: 5s
            timeout: 5s
            retries: 5

    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            DATABASE_URL: postgresql://kolesiki_user:your_password@db:5432/kolesiki_db

volumes:
    postgres_data:
